project_id = "lomqlmqsoyayuegheetv"

[functions.create-stripe-checkout]
verify_jwt = false

[functions.create-ziina-checkout]
verify_jwt = false

[functions.track-visitor]
verify_jwt = false

[functions.verify-ziina-payment]
verify_jwt = false
